version: '3'

services:
  witsdev-spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: witsdev-spark-master
    hostname: witsdev-spark-master
    ports:
      - "27080:8080"
      - "27077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==witsdev-spark-master"
  witsdev-spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: witsdev-spark-worker-1
    hostname: witsdev-spark-worker-1
    depends_on:
      - witsdev-spark-master
    ports:
      - "27081:8081"
    environment:
      - "SPARK_MASTER=spark://witsdev-spark-master:7077"
      - "constraint:node==witsdev-spark-master"
  witsdev-spark-worker-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: witsdev-spark-worker-2
    hostname: witsdev-spark-worker-2
    depends_on:
      - witsdev-spark-master
    ports:
      - "27082:8081"
    environment:
      - "SPARK_MASTER=spark://witsdev-spark-master:7077"
      - "constraint:node==witsdev-spark-worker-1,witsdev-spark-worker-2"