version: '3'

services:
  # inner baksvr registry center
  # zookeeper cluster
  witsdev-zoo1:
    image: zookeeper
    container_name: witsdev-zoo1
    restart: unless-stopped
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  witsdev-zoo2:
    image: zookeeper
    container_name: witsdev-zoo2
    restart: unless-stopped
    ports:
      - 22182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  witsdev-zoo3:
    image: zookeeper
    container_name: witsdev-zoo3
    restart: unless-stopped
    ports:
      - 22183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
